config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'visitors#index'
  resources :projects, only: [:index] do
    get '/page/:page', to: 'projects#index', on: :collection 
    
  end
  resources :contacts, only: [:new, :create]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/concerns/shared_scopes.rb
module Shared_scopes
  extend ActiveSupport::Concern
  included do
  scope :recent, -> { order("updated_at desc") }
  end  
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  

  def headers
    {
      :subject => "Contact Form",
      :to => "infokverko@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Shared_scopes
  has_many :project_images
  
  validates :body, :title, :url, presence: true
  validates :body, length: {maximum: 65535}
  validates :title, length: {maximum: 255}
end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base
  belongs_to :project

  has_attached_file :image, :styles => { :original => "800x1300>", :medium => "300x700>", :thumb => "100x150>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :image , message: 'Image attached'
  validates_attachment_size :image, :less_than => 2.megabytes, message: 'Image has valid size'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  http_basic_authenticate_with name: "admin", password: "kverko_admin" if Rails.env.production?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_defaults

  
  # Sets defaults projects
  def set_defaults
    @last_projects = Project.limit(3).reverse_order
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if verify_recaptcha(model: @contact, message: "reCAHPTCHA OK") && @contact.deliver
      redirect_to root_path, notice: 'Thank you for your letter'
    else
      render :new, notice: 'Sorry, a system error, please try again later'
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  decorates_assigned :project, :projects
  respond_to :html

  def index
    @projects = Project.paginate(page: params[:page], per_page: 6).reverse_order
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contacts/new.html.haml
.col-md-8.col-md-offset-2
  %h3 CONTACT US
  = simple_form_for @contact do |f|
    = f.input :email, required: true, input_html: { class: "form-control" }, placeholder: 'E-mail'
    = f.input :name, required: true, input_html: { class: "form-control" }, placeholder: 'Name'
    = f.input :message, as: :text, required: false, input_html: { class: "form-control" }, placeholder: 'Your message'
    = recaptcha_tags  :display => {theme: 'white'}
    = f.button :submit, 'SEND A MESSAGE', {class: 'btn btn-lg btn-primary'}

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0

#navbar.navbar-collapse.collapse
  %ul.nav.navbar-nav.navbar-right
    %li.animated.infinite.pulse
      = link_to t('defaults.home', class: 'navbar-brand'), root_path
    %li.animated.infinite.flash
      = link_to t('defaults.service', class: 'navbar-brand'), root_path
    %li.animated.infinite.shake
      = link_to t('defaults.projects', class: 'navbar-brand'), projects_path
    %li.animated.infinite.swing
      = link_to t('defaults.contacts', class: 'navbar-brand'), new_contact_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Kverko'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Kverko'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    / = javascript_include_tag 'ckeditor/ckeditor.js'
    = csrf_meta_tags
    %link{:href => "/assets/favicon.ico", :rel => "icon", :type => "image/x-icon"}/
    %link{:href => "/assets/favicon.ico", :rel => "shortcut icon", :type => "image/x-icon"}/
  %body
    %p.notice= notice
    %p.alert= alert
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/project_images/_project_image.html.haml
= project_image.img_link_tag

app/views/projects/_project.html.haml
.proj.col-md-3
  -value = project.title
  %h2{id: "#{value}"}
    = project.title
  .pr
    = render project.project_images
    %p= raw project.body
    %h4 Domain:
    %p= link_to project.title, project.url

app/views/projects/index.html.haml
/ .nav-page
/= render 'layouts/navigation'
.clear
.container-projects.col-md-12
  %h1= t('.title')
  .gallery.clearfix

    = render projects
  = will_paginate @projects
/ .clear
/ = render 'pages/contact'

app/views/visitors/index.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.col-lg-12
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("home/logo.png", onmouseover: "this.src='#{asset_path('home/Logo.png')}'", onmouseout: "this.src='#{asset_path('home/logo.png')}'", class: "logo"), root_path
 
    = render 'layouts/navigation'

    %h1.home_title1
      = t('defaults.title')
    %h3.home_title2
      = t('defaults.ruby')
    %h3.home_title3
      = t('defaults.development') 
    = link_to t('defaults.button_text'), root_path, class: "btn-primary btn-lg how"
    = link_to image_tag("home/arrow_down.png", class: "mouse")